'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("History.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0048() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_0048", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Павлодарцы – Герои Советского Союза Мечтая о достойном будущем, давайте помнить
        '''
        '''о достойном прошлом. Н.А.Назарбаев Солдат, офицер, защитник Родины… Когда звучат эти слова, сразу представляешь людей, причастных к корпусу мужественных, сильных защитников Родины. Слава красных командиров, легендарных комиссаров, Героев Советского Союза, слава всемирно известных полководцев озаряет солдатские и офицерские погоны. Все ли мы помним имена наших героев? Знаем ли мы, чьими именами названы улицы города? А среди ни [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _1() As String
            Get
                Return ResourceManager.GetString("_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Ади́ль Оралбе́кович Жале́лов (каз. Әділ Оралбекұлы Жәлелов, род. 3 июня 1990 года, Ленинский, Казахская ССР), более известный под сценическим псевдонимом Скриптони́т (англ. Scriptonite) — казахстанский рэп-исполнитель и битмейкер, участник творческого объединения Gazgolder. 
        '''
        '''Впервые громко заявил о себе в 2014 году видеоклипом на песню «VBVVCTND», спустя полтора года выпустил свой дебютный альбом «Дом с нормальными явлениями», который стал одним из самых удачных русскоязычных рэп-альбомов 2015 года.
        '''
        '''В [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _10() As String
            Get
                Return ResourceManager.GetString("_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _11111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_11111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _111111() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_111111", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _111k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_111k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Сабит Донентаев (каз. Сәбит Дөнентаев) (1894 — 23 мая 1933) — казахский поэт-сатирик, публицист, общественный деятель. 
        '''
        '''Биография
        '''
        '''Родился в 1894 году в Аксуской волости Павлодарского уезда Семипалатинской области в семье бедного скотовода Донентая Жаналина из казахского племени Аргын среднего жуза. Получил мусульманское образование в медресе Касым-ходжи Ертысбаева. На становление Донентаева как поэта повлияли произведения Крылова, татарского классика Габдуллы Тукая и классика казахской поэзии Абая Кун [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _112() As String
            Get
                Return ResourceManager.GetString("_112", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Султанмахму́т Торайгы́ров (каз. Сұлтанмахмұт Торайғыров, 29 октября 1893, Баянаул, Степное генерал-губернаторство — 21 мая 1920, аул Шокпыт, Павлодарская область) — казахский поэт-демократ. 
        '''
        '''Биография
        '''Султанмахмут Аубакирулы Торайгыров родился в 1893 году на территории сегодняшнего Кзылтуского района Северо-Казахстанской области. Его отец, Аубакир был человеком довольно бедным. Вынужденный работать по найму, он покинул родные места и переехал в аул близ Омска к своему богатому зятю, где женился на его р [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _12() As String
            Get
                Return ResourceManager.GetString("_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Па́вел Никола́евич Васи́льев (23 декабря 1909 (5 января 1910), Зайсан, Семипалатинская губерния — 16 июля 1937, Москва) — русский советский поэт, родоначальник (по определению С. Клычкова) «героического периода»[1] в русской литературе — «эпохи побеждающего в человеческой душе коммунизма». 
        '''
        '''Биография
        '''
        '''Родился 5 января 1910 года (23 декабря 1909 года по ст. ст.) в Зайсане (ныне Республика Казахстан)[2]. Отец — Николай Корнилович Васильев (1886—1940), сын пильщика и прачки, выпускник Семипалатинской учит [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _13() As String
            Get
                Return ResourceManager.GetString("_13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Халижан Нургожаевич Бекхожин (Халижан; также Халимжан Нургажаевич) (15 декабря 1913 года, Павлодар — 2 октября 1990 года, Алматы) — казахский советский поэт, драматург, переводчик, критик. 
        '''
        '''Член Союза писателей Казахстана (1936), Народный писатель КазССР (1986), лауреат Государственной премии КазССР (1978). Почётный гражданин Павлодара (1985). Участник Великой Отечественной войны. 
        '''
        '''Биография
        '''Окончил КазПИ (1938). В 1932—1934 гг. сотрудник редакции павлодарской газеты «Колхоз», где опубликовал первые  [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _14() As String
            Get
                Return ResourceManager.GetString("_14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Мудряк Мария Александровна (родилась 6 апреля 1994 в Павлодарской области, в г. Павлодаре) — казахстанская оперная певица.
        '''
        '''Биография и карьера
        '''
        '''Обучаться вокалу начала в 3 года во Дворце Школьников г. Павлодара, там же состоялось её первое выступление на сцене.
        '''
        '''В 5 лет поступила на фортепьянное отделение музыкальной школы № 1 г. Павлодара.
        '''
        '''В 2004 году в возрасте 10 лет переехала в Италию, в г. Милан обучаться оперному вокалу, где и проживает до настоящего времени.
        '''
        '''В Италии получила среднее и в [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _15() As String
            Get
                Return ResourceManager.GetString("_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Родился 20 января 1952 года в Славгороде Алтайского края.
        '''
        '''Заслуженный деятель искусств РФ (2001).
        '''
        '''Народный артист Российской Федерации (2010).
        '''
        '''Учился в школах Славгорода и Павлодара (Казахская ССР). После окончания школы в 1969-1970 гг. работал художником-конструктором Павлодарского тракторного завода. 
        '''
        '''Большое влияние на жизненное становление и закалку характера Владимира в школьные годы оказало его участие в молодёжной организации «Гринабель» под руководством Виталия Ерёмина: 
        '''
        '''«Я тогда был  [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _16() As String
            Get
                Return ResourceManager.GetString("_16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Каныш Имантаевич Сатпаев каз. Қаныш Имантайұлы Сәтбаев (31 марта [12 апреля] 1899, аул Аккелинской волости[1], Павлодарский уезд, Российская империя — 31 января 1964, Москва) — советский академик, геолог, организатор науки и общественный деятель[2]. Один из основателей советской металлогенической науки, основоположник казахстанской школы металлогении[3][4]. 
        '''
        '''Доктор геолого-минералогических наук (1942), профессор (1950), академик АН Казахской ССР (1946), действительный член АН СССР (1946), первый президен [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _17() As String
            Get
                Return ResourceManager.GetString("_17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Шафи́к Чо́кинович Чо́кин (каз. Шапық Шоқыұлы Шокин; 1 октября 1912 год, Баянаульский район Павлодарской области — 4 июля 2003 год, Алма-Ата) — советский и казахстанский учёный-энергетик. Основатель энергетической науки в Казахстане[1]. Депутат Верховного Совета СССР 6 созыва, заместитель Председателя Совета Союза Верховного Совета СССР 6 созыва, в 1964—1967 годы президент Академии наук Казахстана. Основатель и первый директор Казахского научно-исследовательского института энергетики. Академик АН КазССР (195 [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _18() As String
            Get
                Return ResourceManager.GetString("_18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Зеин Жунусбекович Шашкин (каз. Зеин Жунусбекұлы Шашкин; 31 декабря 1912, аул Бозшаколь, Баянаульский округ, Семипалатинская область, Российская империя — 29 марта 1966, Алма-Ата, Казахская ССР, СССР) — казахский советский писатель, драматург, врач, ученый. 
        '''
        '''Биография
        '''Зеин Шашкин родился в 1912 году в местности Бозшаколь Баянаульского района Павлодарской области. Происходит из рода Бегендык племени Аргын[1]. С 1920 по 1930 годы учился в средней школе города Павлодара. В 1930—1933 годах проходил учёбу в М [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _19() As String
            Get
                Return ResourceManager.GetString("_19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Роза Мукатаева - казахстанская певица, одна из самых популярных участниц телевизионных шоу «X-Фактор» и «Қазақстан дауысы».
        '''Роза Мукатаева полюбилась казахстанцам благодаря своим выступлениям и участию в телешоу «Х-Фактор» и «Қазақстан дауысы». После окончания проектов певица работала с продюсерами Али Окаповым и Ерланом Алимовым, участвовала в вокальных конкурсах, снималась в рекламе и популярных программах на ТВ.
        '''«Чудо-голос из Павлодара», «казахстанская Лара Фабиан», «девочка-сенсация» – так ее окрести [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _2() As String
            Get
                Return ResourceManager.GetString("_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Иса Байзаков (1900, современный Иртышский район (Павлодарская область) Павлодарская область — 1946, Алма-Ата, Казахская ССР, СССР) — казахский народный акын, певец, композитор. Награждён орденом Трудового Красного Знамени.
        '''
        '''Биография Родился в селе Ульгули Иртышского района. Происходит из подрода Альке рода Куандык (внутри алтай-карпыки) племени Аргын. С детства Ису в семье окружала атмосфера творчества, которая была создана благодаря подлинному интересу и любви к искусству его отца Байзака и матери Газиз [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _20() As String
            Get
                Return ResourceManager.GetString("_20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Жусипбек Аймауытов (Аймаутов) (8 марта 1889 года село Баянаул, Павлодарский уезд, Семипалатинская область, Российская империя — 21 апреля 1930 года, Москва, РСФСР, СССР) — многожанровый писатель, основоположник драмы и романа на казахском языке, учёный, просветитель, педагог, психолог. 
        '''
        '''Биография
        '''
        '''Родился в 1889 году в Баян-Аульском районе Павлодарского уезда. Жил в бедной семье. Его прадеды Дандебай и Куан были уважаемыми и образованными людьми из знатного рода. С детства обучался арабской грамоте, ку [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _21() As String
            Get
                Return ResourceManager.GetString("_21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на  Шаке́н Кенжетаевич Айма́нов (настоящее имя — Шахкерим (Шаһкерім[1]каз. Шәкен Кенжетайұлы Айманов; 1914—1970) — советский и казахский актёр и режиссёр театра и кино. Народный артист СССР (1959).  
        '''
        '''Родился 2 (15) февраля 1914 год в Баян-Ауле (по другим источникам — в Баянаульском районе[2]) (ныне — в Павлодарской области Казахстана) в семье крестьянина-скотовода. Происходит из рода Айдабол, в составе рода Суюндык племени АргынСреднего жуза.
        '''
        '''В 1928 году окончил среднюю школу[3]. В 1931—1933 годах учился [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _221() As String
            Get
                Return ResourceManager.GetString("_221", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _222() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_222", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2222() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2222", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _22222() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_22222", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _222222() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_222222", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _222k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_222k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Григо́рий Никола́евич Пота́нин (22 сентября [4 октября] 1835, Ямышевская крепость Иртышской линии, Омская область, Российская империя — 30 июня 1920, Томск, РСФСР) — российский географ, этнограф, фольклорист, ботаник, публицист; общественный деятель — один из идеологов и основателей общественно-политического течения Сибирское областничество. Действительный член ИРГО. Почётный член ЗСОИРГО.
        '''
        '''Происхождение Григорий Николаевич Потанин принадлежал старинному сибирскому казачьему роду. По одной из версий праде [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _23() As String
            Get
                Return ResourceManager.GetString("_23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Алексе́й Ива́нович Булдако́в (26 марта 1951, Макаровка, Алтайский край, РСФСР, СССР — 3 апреля 2019, Улан-Батор, Монголия) — советский и российский актёр театра и кино, народный артист Российской Федерации (2009). 
        '''
        '''Биография
        '''
        '''Родился 26 марта 1951 года в селе Макаровка Ключевского района Алтайского края. Затем семья переехала в Павлодар. Занимался боксом и классической борьбой. 
        '''
        '''Окончил театральную студию при Павлодарском драматическом театре им. А. П. Чехова (1969). Работал на Павлодарском тракторн [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _24() As String
            Get
                Return ResourceManager.GetString("_24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Ермуха́н Бекмаха́нович Бекмаха́нов родился 1915 году в Баянаулском районе Павлодарской области Казахстана. Учёный-историк, член-корреспондент Академии Наук Казахской ССР. 
        '''
        '''Доктор исторических наук (1948), профессор (1949), член-корреспондент АН Казахской ССР (1962). 
        '''
        '''Окончил в 1937 году Воронежский педагогический институт. Научный сотрудник, директор Научно-исследовательского института педагогики при Наркомпросе (1937—1945), старший научный сотрудник, заместитель директора Института истории, археологи [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _25() As String
            Get
                Return ResourceManager.GetString("_25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Жаяу Муса Байжанулы (18 октября 1835 - 31 июля 1929) - казахский акын, народный композитор, певец.
        '''
        '''Биография Родился в 1835 году близ озера Жасыбай, в Баянаульском районе Павлодарской области Казахстана. Имя отца было Байжан, а мать звали Нагжан, отец Жаяу Мусы Байжан был бедняком. Происходит из подрода Айдабол рода Суйиндык племени Аргын Среднего жуза. Мальчик рано испытал тяготы сиротства, оставшись в детстве без матери. После смерти первой жены Байжан взял себе в токал скандальную и сварливую девушку  [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _26() As String
            Get
                Return ResourceManager.GetString("_26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Дми́трий Полика́рпович Бага́ев (5 сентября 1884, с. Туманы, (ныне Кировской области), Российская империя — 23 июля 1958, Павлодар, Казахская ССР) — фотограф, краевед, основатель и первый директор областного краеведческого музея.
        '''
        '''Образование
        '''
        '''Окончил кратковременные курсы у омского фотографа Коркина (1901—1903) и фотокурсы в Москве (1928). 
        '''
        '''Карьера
        '''
        '''⦁	С 1905 г. — владелец фотостудии.
        '''
        '''⦁	Был избран членом Тамбовского фотографического общества (⦁	1912).
        '''
        '''⦁	Служил в армии (г. Новониколаевск, ⦁	191 [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _27() As String
            Get
                Return ResourceManager.GetString("_27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Альке́й Хака́нович Маргула́н (каз. Әлкей Хақанұлы Марғұлан (10 мая 1904 года, аул № 2 Баянаульского уезда Семипалатинской области, Степное генерал-губернаторство, Российская империя — 14 января 1985 года, Алма-Ата, Казахская ССР, СССР) — казахский учёный-археолог, востоковед, историк, литературовед, искусствовед. 
        '''
        '''Доктор филологических наук (1946), академик АН КазССР (1958), профессор (1960), заслуженный деятель науки КазССР (1961), основоположник казахстанской школы археологии и этнографии 
        '''
        '''Биография [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _28() As String
            Get
                Return ResourceManager.GetString("_28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Дата   рождения    25 декабря 1901
        '''
        '''Место рождения    Баянаул
        '''
        '''Дата   смерти         22 декабря 1985 
        '''
        '''Место смерти         Алма-Ата
        '''
        '''Страна                    СССР     
        '''
        '''Научная   сфера     Химия
        '''
        '''Альма - матер         Сибирский институт сельского хозяйства и лесоводства
        '''
        '''Учёная степень       Доктор   химических наук
        '''
        '''Учёное звание	Академик АН Казахской ССР
        '''
        '''Абике́н Бекту́рович Бекту́ров (12(25) декабря 1901, Баянаул, Российская империя — 22 ноября 1985, Алма-Ата) — химик, академик АН Каз [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _29() As String
            Get
                Return ResourceManager.GetString("_29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Машхур Жусуп Копеев (1858 — 1931) — казахский поэт, мыслитель, историк, этнограф, востоковед и собиратель устного народного творчества казахского народа.
        '''
        '''Биография
        '''
        '''Обучался в аульной школе. Происходит из подрода Күлік рода Суйиндык племени Аргын Среднего жуза. В 1870 году учился в Бухарском медресе хазрета Камара, после чего он едет в другие районы Северного и Центрального Казахстана, чтобы собирать произведения устного народного творчества. Он посетил известные всему Казахстану места: Караоткел, Атба [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _3() As String
            Get
                Return ResourceManager.GetString("_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Настоящее имя выдающего композитора, народного артиста СССР, классика казахской музыкальной культуры Мухамедсалим Тулебаев. Мукан — так коротко и ласково называли его родственники и сверстники. Это имя закрепилось за ним на всю жизнь. Родился Мукан Тулебаев 13 марта 1913 года в ауле Самеке (Карашаган) Бурлютобинского (ныне Саркандского) района Алматинской области. 
        '''
        '''Музыкальное детство 
        '''
        '''Музыкальность и поэтический дар Мукан унаследовал от матери. Она выросла в многодетной семье, где царила творческая а [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _30() As String
            Get
                Return ResourceManager.GetString("_30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Государственный деятель, ученый, просветитель, поэт, публицист, реформатор национальной письменности, основоположник казахской лингвистики и литературоведения. БАЙТУРСЫНОВ Ахмет (Ахмет Байтурсынулы) (28.01.1873, ныне а. Сарытубек Жангельдинского района Костанайской области — 08.12.1938, Алматы), государственный деятель, ученый, просветитель, поэт, публицист, реформатор национальной письменности, основоположник казахской лингвистики и литературоведения, один из руководителей национально-освободительного движ [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _31() As String
            Get
                Return ResourceManager.GetString("_31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Выпускник школы-лицея №8 для одаренных детей (учитель Ганелин Д.Г.) в Павлодаре. Серебряный призер Международной математической олимпиады 2002 года (г. Глазго,  Шотландия), победитель 2003 года (г. Токио,  Япония) и 2004 года (г.Афины, Греция). Выпускник Технологического института (Массачусетс, США). Доктор PHD, сотрудник компании Google (Калифорния, США). Это все про Есенова Куата. 
        '''
        '''Куат Есенов, названный президентом Казахстана “золотым мальчиком”  и попавший в Книгу рекордов Гиннесса как самый титулова [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _32() As String
            Get
                Return ResourceManager.GetString("_32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _333() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_333", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3333() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3333", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _33333() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_33333", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _333333() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_333333", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _333k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_333k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на ОМИРУЛЫ ЖАСЫБАЙ БАТЫР (приблизительно 1716-1741 гг., ХVIII в.) - легендарный казахский батыр, сражавшийся против джунгар. 
        '''
        '''Происходит из рода - аргын, племени - басентиин. НОВОСТИ ПО ТЕМЕ Чудом остались живы: истории полицейских Туркестанской области Спасшего от гибели мать и ребенка пограничника наградили в СКО Спасших детей полицейских наградили в Северном Казахстане Родился в Баянауле (Павлодарская область). Его отец Омир был красноречивым и остроумным человеком. Его мать - сестра знаменитого казахско [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _4() As String
            Get
                Return ResourceManager.GetString("_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _444() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_444", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4444() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4444", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _44444() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_44444", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _444444() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_444444", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _444k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_444k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на  Никитенко Виталий Петрович (1936 – 2007 г.г.) – педагог с большой буквы. Лицей № 8, которым высокопрофессионально руководил Виталий Петрович, стал одним из лучших образовательных учреждений в городе, в Республике и ближайших регионах России. 
        '''
        ''' 
        '''
        '''Слава лицея по праву связана с именем и деятельностью Виталия Петровича Никитенко. В 1990 году он стоял у истоков идеи создания школы для одаренных детей и до последних дней своей жизни жил духом и буднями лицея , гордился его успехами. Имя Первого директора н [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _5() As String
            Get
                Return ResourceManager.GetString("_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _55() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_55", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _555() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_555", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5555() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5555", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _55555() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_55555", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _555555() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_555555", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _555k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_555k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Халижан Нургожаевич Бекхожин (Халижан; также Халимжан Нургажаевич) (15 декабря 1913 года, Павлодар — 2 октября 1990 года, Алматы) — казахский советский поэт, драматург, переводчик, критик. 
        '''
        '''Член Союза писателей Казахстана (1936), Народный писатель КазССР (1986), лауреат Государственной премии КазССР (1978). Почётный гражданин Павлодара (1985). Участник Великой Отечественной войны. 
        '''
        '''Биография
        '''
        '''Окончил КазПИ (1938). В 1932—1934 гг. сотрудник редакции павлодарской газеты «Колхоз», где опубликовал первы [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _6() As String
            Get
                Return ResourceManager.GetString("_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _66() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_66", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _666() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_666", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6666() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6666", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _66666() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_66666", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _666k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_666k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Майра Шамсутдинова (каз. Майра Уалиқызы; 1890, Павлодар, Российская империя (ныне Казахстан) — 25 января 1927, Павлодар, СССР) — казахский композитор и народная певица.
        '''
        '''Биография
        '''
        '''Родилась в 1890 году в городе Павлодар. С 13 лет Майра выступала перед широкой аудиторией.
        '''
        '''Творчество
        '''
        '''Широкий диапазон голоса позволял ей исполнять классические, народные песни, сочинения современников и собственные произведения.
        '''
        '''Она мастерски пела на казахском, татарском и русском языках. Демонстрировала свое искусс [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _7() As String
            Get
                Return ResourceManager.GetString("_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _77() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_77", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _777() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_777", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7777() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7777", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _77777() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_77777", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _777k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_777k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Ганелин Давид Григорьевич – педагог высокой эрудиции, владеющий глубокими знаниями в области математики, психологии и педагогики, умеющий выявлять и развивать интеллектуальные способности детей.
        '''
        '''Высокая работоспособность и научный подход к организации учебной деятельности учащихся помогли учителю добиваться наивысших результатов в организации процесса познания и научного исследования.
        '''
        '''  В 1944 году, когда освободилась Белоруссия, семья вернулась назад, в город Ельск Гомельской области. Когда война зак [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _8() As String
            Get
                Return ResourceManager.GetString("_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _88() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_88", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8888() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8888", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _88888() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_88888", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Буха́р жыра́у Калкама́нулы (каз. Бұқар жырау Қалқаман ұлы), (1693 — 1787,по другим данным — 1668—1781) — казахский акын, жырау, бий, видный представитель казахского устно-поэтического творчества. Главный советник легендарного казахского хана Абылая.
        '''
        '''Биография
        '''
        '''Родился Бухар жырау в 1668 (по другим данным 1685 или даже 1693) году. Происходит из подрода Каржас рода Суйиндык племени Аргын Среднего жуза.
        '''
        '''Бухар жырау родился на территории нынешней Республики Узбекистан в урочище Елибай вблизи древнего го [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property _9() As String
            Get
                Return ResourceManager.GetString("_9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _99() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_99", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9999() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9999", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _99999() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_99999", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bas1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bas1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property comeback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comeback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kaz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kaz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kor1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kor1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mur2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mur2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Инструкция к Интерактивному музею &quot;Наследие Великой степи&quot;
        '''
        ''' • Коротко о главном
        '''В данном разделе представлены краткие описания о каждом пункте статьи Н. А. Назарбаева &quot;7 граней Великой степи&quot;.
        '''
        '''• Архив 20-25
        '''В данном разделе собран материал о знаменитых личностей Павлодарского Прииртышья от средних веков до современности.
        '''
        '''• Практическая работа
        '''В данном разделе Вам предлагают проверить себя на зания теории и практики после изучения разделов &quot;Коротко о главном&quot; и &quot;Архив 20-25&quot;.
        '''
        '''Часто задаваемые  [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property Novy_textovy_dokument__2_() As String
            Get
                Return ResourceManager.GetString("Novy_textovy_dokument__2_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property o16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("o16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Дальним передвижениям и тебенёвке.    
        '''Холодам.
        '''Быстрому набору веса.
        '''Передвижению по пустыне.
        '''Бегазы-Дандыбаевская культура.
        '''Ботайская культура.
        '''Тамгалинская культура.
        '''Атасуская культура.
        '''III-II тыс.до н.э.
        '''II-I тыс.до н.э. 
        '''XVIII-VIII вв.до н.э.
        '''VIII в.до н.э.-VI в.н.э
        '''«Геометрический».
        '''«Цветочный».
        '''«Полихромный».
        '''«Смешанный».
        '''«Воинские».
        '''«Женские».
        '''«Царские».
        '''«Жрецкие».
        '''«Курганы с двойными захоронениями».
        '''«Малые».
        '''«Царские».
        '''«С усами».
        '''Уык.
        '''Кереге.
        '''Шанырак.
        '''Кошма.
        '''Землянка.
        '''Ш [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property Otvety() As String
            Get
                Return ResourceManager.GetString("Otvety", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property phootttnenp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phootttnenp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Дальним передвижениям и тебенёвке.    
        '''Бегазы-Дандыбаевская культура.
        '''VIII в.до н.э.-VI в.н.э
        '''«Полихромный».
        '''«Царские».
        '''«С усами».
        '''Кереге.
        '''Куйме.
        '''Китай.
        '''«Звериный стиль».
        '''Ел-хан.
        '''Лошадь.
        '''Экибастуз.
        '''Жайляу.
        '''Тюрк..
        '''</summary>
        Friend ReadOnly Property Pravilnye_otvety() As String
            Get
                Return ResourceManager.GetString("Pravilnye_otvety", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на С переходом к кочевому скотоводству увеличилось число лошадей и овец, т.к. они были приспособлены к:
        '''В эпоху бронзы на территории Казахстана на смену Андроновской культуре пришла кочевая:
        '''Эпоха железа охватывает:
        '''Наряду со «звериным стилем» в Центральном Казахстане, начиная с VII-V вв.до н.э., развивается стиль:
        '''Только в Зайсанском районе Вост.Каз-на расположено около 200 крупных курганов эпохи раннего железа, 50 из них носят название:   
        '''Для Центрального Казахстана периода раннего железа характерны ку [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property Voprosy() As String
            Get
                Return ResourceManager.GetString("Voprosy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property zastavka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zastavka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
